### ISSUE TITLE
ステージ構成について

### ISSUE THREAD

**Issue by saitoutatuhiro** [yuckune/Ball-Control-Game#12]
1－8のステージ構成の例を渡します。

Outlookのメールを見てください。

この通りに構成してもよいですし、参考にして新たにステージを作成してもかまいません。

**Comment by saitoutatuhiro** [comment]
> 1－8のステージ構成の例を渡します。
> 
> Outlookのメールを見てください。
> 
> この通りに構成してもよいですし、参考にして新たにステージを作成してもかまいません。

**Comment by saitoutatuhiro** [comment]
1－8のステージ構成の例を渡します。

Outlookのメールを見てください。

この通りに構成してもよいですし、参考にして新たにステージを作成してもかまいません。

**Comment by yuckune** [comment]
[stages.xlsx](https://github.com/yuckune/Ball-Controll-Game/files/3389708/stages.xlsx)

必要な機能が完成したら反映します。
提案ありがとうございます。

**Comment by yuckune** [comment]
反映しました。
変更、追加はjson形式でできます。
