### ISSUE TITLE
実際の授業で使えるかについて

### ISSUE THREAD

**Issue by saitoutatuhiro** [yuckune/Ball-Control-Game#16]
急な話ですいません。9月19日に小学生むけに授業でつかってみたいということでした。

１、プログラミングアプリ（案）の「（案）」の削除
２、説明をすべて削除（一番下の遊び方を残す）
３、ステージ9、10、11、12を削除

利用方法はタブレットで動作させたいため、.exe化できればお願いします。
exeファイルのほかにjavascriptコードもお願いします。

**Comment by yuckune** [comment]
リリースブランチに作りました。
[https://github.com/yuckune/Ball-Control-Game/tree/release](https://github.com/yuckune/Ball-Control-Game/tree/release)
clone or download からファイルをダウンロードし、ブラウザでindex.htmlを開く
(最新版ChromeとFirefoxで動作を確認)

exe化はelectronを使ってやってみます。

**Comment by yuckune** [comment]
releaseブランチにexeファイルを置きました。
注意として、セキュリティに関する通告が出る可能性があります。
こちらのタブレットでは動作が確認できました。
